kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./build/Dockerfile
  context: .

spec:
  operator: xgboost
  image: image
  command: "python3 -u main.py --operator=xgboost --sleep=3600 --tb-write=True"
  activeDeadlineSeconds: 3600
  tensorboard:
    enabled: true
  types:
    worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 1
        shmSizeGB: 0
        accelerators: # optional
          gpu:
            count: 0
            type: gpu
            product: nvidia-tesla-t4

